version: '3.8'

services:
  archivio:
    build:
      context: .               # "." perché ora sei *dentro* la cartella archivio
    container_name: archivio
    ports:
      - "8080:8080"
    networks:
      - rete-app

  chiamaarchivio:
    build:
      context: ../chiamaarchivio   # percorso relativo da archivio/ a chiamaarchivio/
    container_name: chiamaarchivio
    ports:
      - "8081:8081"
    depends_on:
      - archivio
    networks:
      - rete-app

networks:
  rete-app:
    driver: bridge
